### ISSUE TITLE
Build system – hatchling or setuptools?

### ISSUE THREAD

**Issue by hollandjg** [INTERSECT-training/packaging#14]
Hatchling is used without motivation throughout. 

- [x] Decide whether to:
  - Keep hatchling
  - Switch to PDM, or Setuptools 
- [x] Implement change if necessary

**Comment by henryiii** [comment]
I'd stick with Hatchling. It's the most popular purely PEP 621 backend by far, and has an extensive plugin system so it's the only one that is poised to scale to handle as much as setuptools can (with horrible hacking!). You can use PDM with hatchling, so I'm guessing you meant pdm-backend above. Setuptools is much harder to configure, produces awful tracebacks if something goes wrong, and is 2-3x slower than hatchling. `packaging.python.org`'s tutorial defaults to hatchling these days. Many of the PyPA projects use Hatchling now too (flit-core is used if bootstrapping is important, but otherwise, it's mostly hatchling)

**Comment by hollandjg** [comment]
Sounds good to me! Hatchling it is.
